### ISSUE TITLE
[1.12] Crash with Player Weight

### ISSUE THREAD

**Issue by MasterEnderman** [MennoMax/astikor-carts#21]
Crash-Report: https://paste.dimdev.org/etapebaduc.mccrash
Astikor Carts: 0.1.2.2
Player Weight: 1.4
Forge: 14.23.5.2815

Already reported to the author of Player Weights aswell: https://github.com/TinyModularThings/Player-Weight/issues/10

The crash occurs each time i try to sit into a cargo cart.

**Comment by MennoMax** [comment]
Thank you, I might've messed something up there. Will look into this immediately.

**Comment by Speiger** [comment]
Since you want to fix it its this line:
https://github.com/MennoMax/astikor-carts/blob/master/src/main/java/de/mennomax/astikorcarts/entity/AbstractDrawnInventory.java#L18

This is a simple loading order issue since references do not update.
Just have a setInventory function that creates the capabilities or deletes it based on what was injected, and have the hasCapability have a != null check.

That should speedup the issue fix

**Comment by MennoMax** [comment]
Sorry, I got distracted - will now push and upload the fix for this issue.
